const state={selectedId:null,currentUser:"@tecnico.campo",data:[
{id:1,tag:"ZSH-20GHA10AA401-S12",loop:"XV-20GHA10AA401",service:"WATER SERVICE TO TANK 20GHA10BB001",type:"AA - VÁLVULA",description:"VÁLVULA ON/OFF",date:null,user:null},
{id:2,tag:"ZSL-20GHA10AA402-S12",loop:"XV-20GHA10AA402",service:"WATER SERVICE TO TANK 20GHA10BB001",type:"AA - VÁLVULA",description:"VÁLVULA ON/OFF",date:null,user:null},
{id:3,tag:"ZSH-20GMA10KB003-S12",loop:"XV-20GMA10KB003",service:"NEUTRALIZATION EFFLUENT PIT AUTOMATIC GATE",type:"INTERFACE ELÉTRICA EQUIPAMENTO",description:"VÁLVULA ON/OFF",date:"11/08/2026 14:32",user:"@tecnico.campo"},
{id:4,tag:"ZSL-20GMA10KB004-S12",loop:"XV-20GMA10KB004",service:"NEUTRALIZATION EFFLUENT PIT AUTOMATIC GATE",type:"INTERFACE ELÉTRICA EQUIPAMENTO",description:"VÁLVULA ON/OFF",date:"12/08/2026 09:18",user:"@operador.01"},
{id:5,tag:"PSH-20GMA10BB001-S12",loop:"P-20GMA10BB001",service:"EFFLUENT PIT",type:"PRESSURE SWITCH",description:"CHAVE DE PRESSÃO",date:null,user:null},
{id:6,tag:"LSH-20GMA10BB002-S12",loop:"L-20GMA10BB002",service:"EFFLUENT PIT",type:"LEVEL SWITCH",description:"CHAVE DE NÍVEL",date:null,user:null},
{id:7,tag:"FIC-20GHA10AA401-S12",loop:"FIC-20GHA10AA401",service:"WATER SERVICE TO TANK",type:"INSTRUMENTAÇÃO",description:"CONTROLADOR DE VAZÃO",date:"12/08/2026 15:40",user:"@operador.01"},
{id:8,tag:"TIT-20GHA10BB001-S12",loop:"TIT-20GHA10BB001",service:"TANK TEMPERATURE",type:"INSTRUMENTAÇÃO",description:"TRANSMISSOR DE TEMPERATURA",date:null,user:null},
{id:9,tag:"XV-20GHA10AA410-S12",loop:"XV-20GHA10AA410",service:"WATER SERVICE",type:"AA - VÁLVULA",description:"VÁLVULA ON/OFF",date:"13/08/2026 08:05",user:"@tecnico.campo"},
{id:10,tag:"ZSH-20GHA10AA411-S12",loop:"XV-20GHA10AA411",service:"WATER SERVICE",type:"AA - VÁLVULA",description:"VÁLVULA ON/OFF",date:null,user:null}],logs:[]};
const $=id=>document.getElementById(id);const nowBR=()=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date()).replace(",","");setInterval(()=>$("currentDateTime").textContent=nowBR(),1000);$("currentDateTime").textContent=nowBR();const isDone=i=>!!i.date;
function counters(){let t=state.data.length,d=state.data.filter(isDone).length;$("totalCount").textContent=t;$("doneCount").textContent=d;$("pendingCount").textContent=t-d}
function renderTable(){let q=$("tagSearch").value.trim().toLowerCase(),rows=state.data.filter(i=>i.tag.toLowerCase().includes(q)),body=$("tagTableBody");body.innerHTML="";rows.forEach(i=>{let tr=document.createElement("tr");if(i.id===state.selectedId)tr.classList.add("selected");tr.innerHTML=`<td class="tag-cell">${i.tag}</td><td>${i.loop}</td><td>${i.service}</td><td>${i.type}</td><td>${i.description}</td><td class="date-cell ${i.date?"":"pending-date"}">${i.date||"Pendente"}</td><td class="log-cell">${i.user?`<strong>Realizado / alterado</strong>${i.user}`:"—"}</td>`;tr.onclick=()=>selectItem(i.id);body.appendChild(tr)});$("emptyState").classList.toggle("hidden",rows.length!==0);counters()}
function selectItem(id){state.selectedId=id;let i=state.data.find(x=>x.id===id);if(!i)return;$("selectedTagTitle").textContent=i.tag;$("fieldTag").textContent=i.tag;$("fieldLoop").textContent=i.loop;$("fieldService").textContent=i.service;$("fieldType").textContent=i.type;$("fieldDescription").textContent=i.description;$("fieldPointDate").textContent=i.date||"Não registrado";let b=$("selectedBadge");b.textContent=i.date?"REALIZADO":"PENDENTE";b.className=`tag-badge ${i.date?"done":"pending"}`;$("registerBtn").disabled=false;$("repeatBtn").disabled=!i.date;$("actionMessage").textContent="";renderTable()}
function toast(m){let t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2600)}
function register(overwrite=false){let i=state.data.find(x=>x.id===state.selectedId);if(!i)return;if(i.date&&!overwrite)return toast("Esta TAG já possui uma data. Use “Repetir ponto a ponto” para alterar.");let prev=i.date,d=nowBR();i.date=d;i.user=state.currentUser;state.logs.unshift({tag:i.tag,date:d,user:state.currentUser,action:prev?"Alteração de ponto a ponto":"Registro de ponto a ponto"});selectItem(i.id);$("actionMessage").textContent=prev?`Registro alterado para ${d} por ${state.currentUser}.`:`Ponto a ponto registrado em ${d} por ${state.currentUser}.`;toast(prev?"Ponto a ponto alterado.":"Ponto a ponto registrado.");renderHistory()}
function nav(screen){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active-screen"));$("screen-"+screen).classList.add("active-screen");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.screen===screen));if(screen==="history")renderHistory();scrollTo({top:0,behavior:"smooth"})}
function renderHistory(){let t=state.data.length,d=state.data.filter(isDone).length,p=t-d,pct=t?Math.round(d/t*100):0;$("historyDone").textContent=d;$("historyPending").textContent=p;$("historyTotal").textContent=t;$("donutPercent").textContent=pct+"%";$("legendDone").textContent=d;$("legendPending").textContent=p;$("donutChart").style.background=`conic-gradient(var(--green) 0 ${pct}%,#edf0f4 ${pct}% 100%)`;let c={};state.data.filter(isDone).forEach(i=>{let day=i.date.slice(0,5);c[day]=(c[day]||0)+1});let days=Object.keys(c).slice(-7),max=Math.max(1,...days.map(d=>c[d]));$("barChart").innerHTML=days.map(day=>`<div class="bar-item"><span class="bar-value">${c[day]}</span><div class="bar" style="--height:${Math.max(6,c[day]/max*160)}px"></div><span class="bar-label">${day}</span></div>`).join("")||`<div class="empty-state"><strong>Ainda não há registros por dia.</strong></div>`;let logs=[...state.logs];state.data.filter(isDone).forEach(i=>{if(!logs.some(l=>l.tag===i.tag&&l.date===i.date))logs.push({tag:i.tag,date:i.date,user:i.user,action:"Registro existente"})});logs.sort((a,b)=>b.date.localeCompare(a.date));$("historyLog").innerHTML=logs.slice(0,12).map(l=>`<div class="history-log-row"><span class="time">${l.date}</span><div><strong>${l.action}</strong><span>${l.tag}</span></div><span class="user">${l.user}</span></div>`).join("")||`<div class="empty-state"><strong>Nenhuma alteração registrada.</strong></div>`;$("lastSync").textContent=nowBR()}
$("tagSearch").oninput=()=>{let v=$("tagSearch").value.trim();$("clearSearch").style.display=v?"block":"none";renderTable();if(v){let f=state.data.find(i=>i.tag.toLowerCase().includes(v.toLowerCase()));if(f)selectItem(f.id)}};$("clearSearch").onclick=()=>{$("tagSearch").value="";$("clearSearch").style.display="none";renderTable()};$("registerBtn").onclick=()=>register(false);$("repeatBtn").onclick=()=>$("confirmModal").classList.remove("hidden");["closeModal","cancelModal"].forEach(id=>$(id).onclick=()=>$("confirmModal").classList.add("hidden"));$("confirmRepeat").onclick=()=>{$("confirmModal").classList.add("hidden");register(true)};$("refreshHistory").onclick=()=>{renderHistory();toast("Histórico atualizado.")};$("logoutBtn").onclick=()=>toast("Sessão encerrada. A autenticação real será conectada na próxima etapa.");document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>nav(b.dataset.screen));renderTable();renderHistory();
